name: Test Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    name: Coveralls Report
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip;
          python -m pip install --upgrade wheel;
          python -m pip install --upgrade cpp-coveralls;
      - name: Get HyPhy code
        uses: actions/checkout@v2
      - name: Install and activate miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'hyphy-test-env'
          environment-file: '.coveralls.env.yml'
          condarc-file: '.coveralls.condarc'
      - name: Build HyPhy
        run:
          cmake .;
          make -j HYPHYDEBUG;
          ln -s HYPHYDEBUG hyphy;
          ln -s HYPHYDEBUG HYPHYMP;
      - name: Run unit tests
        run:
          PATH=.:$PATH ./run_unit_tests.sh || true;
      - name: Generate coverage information
        run:
          coveralls --gcov-options '\-lp';
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_token }}
